version: "3.9"
services:
  ws-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    environment:
      APP_WS_SERVER_HOST: "0.0.0.0"
      APP_WS_SERVER_PORT: "8080"
  ws-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    environment:
      APP_WS_SERVER_URL: "ws://172.17.0.1:8080/ws"
    deploy:
      replicas: 10
